declare @name varchar(100) ='ashok,krishna,pardha'

select value from
string_split(@name,',')
where rtrim(value) <>'';




declare @name1 varchar(100)= 'ASHOK KRISHNA PARDHA'

SELECT VALUE
FROM string_split(@NAME1,' ')

WHERE RTRIM(VALUE)<>''

declare @name1 varchar(100)= 'ASHOK KRISHNA PARDHA'

SELECT SUBSTRING(@NAME1,5,16)

declare @name1 varchar(100)= 'ASHOK KRISHNA PARDHA'
SELECT LTRIM(SUBSTRING(@NAME1,5,16))


declare @name1 varchar(100)= 'ASHOK KRISHNA PARDHA'

CREATE TABLE FULLNAME (ID INT ,FULLNAME VARCHAR(100))
INSERT INTO FULLNAME VALUES (1,'      ASHOK KRISHNA PARDHA');

SELECT *FROM FULLNAME


SELECT
FULLNAME,
SUBSTRING(FULLNAME,1,CHARINDEX(' ',FULLNAME,-1)) AS FIRST_NAME,
SUBSTRING(FULLNAME,CHARINDEX(' ',FULLNAME,-1),CHARINDEX(' ',FULLNAME,+1)  ---,(RTRIM(LEN(FULLNAME)))) AS MIDDLENAME,
SUBSTRING(FULLNAME,CHARINDEX(' ',FULLNAME,+1),LEN(FULLNAME)) AS LASTNAME

FROM FULLNAME

SELECT TRIM(CHARINDEX(' ',FULLNAME,+1))
FROM FULLNAME
 'ASHOK KRISHNA PARDHA'
SEL
SELECT
SUBSTRING(FULLNAME,CHARINDEX(' ',FULLNAME),(CHARINDEX('K',FULLNAME,+1))) AS MIDDILE
FROM FULLNAME---,(RTRIM(LEN(FULLNAME)))) AS MIDDLENAME,

SELECT
SUBSTRING(FULLNAME,CHARINDEX(' ',FULLNAME,+1),LEN(CHARINDEX('',FULLNAME,-1))) AS MIDDILE
FROM FULLNAME

SELECT 
LEFT(TRIM(SUBSTRING(FULLNAME,CHARINDEX(' ',FULLNAME,+1),LEN(FULLNAME))) ,
          CHARINDEX(' ',TRIM(SUBSTRING(FULLNAME,CHARINDEX(' ',FULLNAME,+1),LEN(FULLNAME)))))
FROM FULLNAME

SELECT RIGHT(FULLNAME,CHARINDEX(' ',FULLNAME))
FROM FULLNAME


SELECT TRIM(SUBSTRING(FULLNAME,CHARINDEX(' ',FULLNAME,+1),LEN(FULLNAME)))
FROM FULLNAME

SELECT SUBSTRING(FULLNAME,CHARINDEX(' ',FULLNAME,+1),8)
FROM FULLNAME

INSERT INTO FULLNAME VALUES(2,'VAIBHAV NANDA KUMAR')
INSERT INTO FULLNAME VALUES(3,'   VAIBHAV    NANDA     KUMAR')

SELECT CHARINDEX(' ',FULLNAME,-1)
FROM FULLNAME

declare @fullname varchar(100) = '     vaibhav    nanda     kumar'
SELECT 
  LTRIM
  (RTRIM(
    SUBSTRING(
      @FullName,
      CHARINDEX(' ', @FullName) + 1,
      CHARINDEX(' ', @FullName, CHARINDEX(' ', @FullName) + 1) - CHARINDEX(' ', @FullName) - 1
    )
  )) AS MiddleName;


  
  select *into Primenumber





  