select getdate()

declare @getdate date
set @getdate=getdate()


select month( getdate())
select day(getdate())

SELECT DATENAME(MONTH, DATEFROMPARTS(2023, 5, 1)) AS MonthName;
SELECT DATENAME(YEAR, DATEFROMPARTS(2023, 5, 1)) AS YEAR;
SELECT DATENAME(DAY, DATEFROMPARTS(2023, 5, 1)) AS DAY;

SELECT DATENAME(WEEKDAY,GETDATE())  AS DAYNAME

SELECT GETDATE() AS TODAYDATE,
DATENAME(QUARTER,GETDATE())AS QUARTER,
DATENAME(WEEK,GETDATE()) AS WEEKINYEAR,
DATENAME(WEEKDAY,GETDATE())  AS DAYNAME,
DATENAME(DAY,GETDATE()) AS DAY,
DATENAME(YEAR,GETDATE()) AS YEAR,
DATENAME(MONTH,GETDATE()) AS MONTH

SELECT GETDATE() AS TODAYDATE,
DATEPART(QUARTER,GETDATE())AS QUARTER,
DATEPART(WEEK,GETDATE()) AS WEEKINYEAR,

DATEPART(WEEKDAY,GETDATE())  AS DAYNAME,
DATEPART(DAY,GETDATE()) AS DAY,
DATEPART(YEAR,GETDATE()) AS YEAR,
DATEPART(MONTH,GETDATE()) AS MONTH

SELECT DATEPART(DD,GETDATE()) AS ISO


WITH nums AS (
    SELECT TOP (DAY(EOMONTH(GETDATE())))
        ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) - 1 AS n
    FROM master.dbo.spt_values  -- or use another large system table
),
date_series AS (
    SELECT DATEADD(DAY, n, DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 1)) AS dt
    FROM nums
)
SELECT DISTINCT DATEPART(WEEK, dt) AS week_number
FROM date_series
ORDER BY week_number;


SELECT FLOOR((DAY(GETDATE()) - 1) / 7) + 1 AS week_of_month;

SELECT 
    DATEPART(WEEK, getdate())
	- DATEPART(WEEK, '2025-05-01') + 1 AS week_of_month;


SELECT  DATEPART(WEEK, '2025-05-21')
SELECT DATEFROMPARTS(YEAR('2025-05-21'), MONTH('2025-05-21'), 1)
SELECT DATEPART(WEEK, DATEFROMPARTS(YEAR('2025-05-21'), MONTH('2025-05-21'), 1))

SELECT DATENAME(WEEKDAY,DATEADD(MONTH,-1,DATEFROMPARTS(YEAR('2025-05-21'), MONTH('2025-05-21'), 16)))




SELECT
  CURRENT_DATE AS date,
  EXTRACT(DAY FROM CURRENT_DATE) AS day,
  EXTRACT(MONTH FROM CURRENT_DATE) AS month,
  EXTRACT(QUARTER FROM CURRENT_DATE) AS quarter,
  EXTRACT(YEAR FROM CURRENT_DATE) AS year,
  EXTRACT(WEEK FROM CURRENT_DATE) AS week_of_year,
  (EXTRACT(DAY FROM CURRENT_DATE) - 1) / 7 + 1 AS week_of_month
;

SELECT 
    GETDATE() AS [date],
    DAY(GETDATE()) AS [day],
    MONTH(GETDATE()) AS [month],
    DATEPART(QUARTER, GETDATE()) AS [quarter],
    YEAR(GETDATE()) AS [year],
    DATEPART(WEEK, GETDATE()) AS [week_of_year],
    (DAY(GETDATE()) + DATEPART(WEEKDAY, DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 1)) - 2) / 7 + 1 AS [week_of_month]
