use 
pmdb
go 


BEGIN TRANSACTION 

UPDATE DEADLOCKTEST SET VALUE = VALUE + 20 WHERE ID =2

WAITFOR DELAY '00:00:05'

UPDATE DEADLOCKTEST SET VALUE = VALUE + 20 WHERE ID =1

COMMIT;

--SELECT * FROM sys.triggers WHERE parent_id = OBJECT_ID('deadlocktest');
--SELECT @@ROWCOUNT;
----SELECT * FROM DEADLOCKTEST