CREATE PROCEDURE USP_TRANSACTION_2
AS
BEGIN
		BEGIN TRAN
			BEGIN TRY
		UPDATE DEADLOCKTEST SET VALUE = VALUE + 10 WHERE ID =1

        WAITFOR DELAY '00:00:05'

        UPDATE DEADLOCKTEST SET VALUE =VALUE + 10 WHERE ID=2

		COMMIT TRAN
         	SELECT ' TRANSACTION SUCCESSFUL'
            END TRY

			BEGIN CATCH
			     IF (ERROR_NUMBER()=1205)
				 BEGIN
				 SELECT'DEADLOCK TRAN IS FAILED PLS RETRY'
				 END
				 ROLLBACK
			END CATCH
END

EXEC USP_TRANSACTION_2