create procedure USP_Transaction_1
as
BEGIN
		BEGIN TRAN
			BEGIN TRY
				UPDATE DEADLOCKTEST SET VALUE = VALUE + 20 WHERE ID =2
                WAITFOR DELAY '00:00:05'
			    UPDATE DEADLOCKTEST SET VALUE = VALUE + 20 WHERE ID =1

		COMMIT TRAN
			    SELECT 'TRANSACTION SUCCESSFUL'
		    END TRY

		BEGIN CATCH

		  IF (ERROR_NUMBER()=1205)
		
		  BEGIN 
			  SELECT 'DEADLOCK TRANSACTION IS FAILED PLEASE RETRY'
		  END 
		      ROLLBACK
		END CATCH

END

EXEC USP_TRANSACTION_1
