use 
pmdb
go
------FOR MERGE COMMAND

CREATE TABLE STUDENTSOURCE 
( 
STID INT PRIMARY KEY, 
NAME VARCHAR (20) 
) 
INSERT INTO STUDENTSOURCE VALUES (1, 'SMITH') 
INSERT INTO STUDENTSOURCE VALUES (2, 'ALLEN')


CREATE TABLE STUDENTTARGET 
( 
STID INT PRIMARY KEY, 
NAME VARCHAR (20) 
) 
INSERT INTO STUDENTTARGET VALUES (1, ' WARD SMITH ') 
INSERT INTO STUDENTTARGET VALUES (3, 'JOHN') 


SELECT * FROM STUDENTSOURCE;
SELECT *FROM STUDENTTARGET;



MERGE STUDENTTARGET T USING STUDENTSOURCE S
ON T.STID=S.STID
WHEN MATCHED THEN
UPDATE SET T.NAME=S.NAME
WHEN NOT MATCHED THEN
INSERT (STID,NAME) VALUES(S.STID,S.NAME);

MERGE STUDENTTARGET T
USING STUDENTSOURCE S
ON T.STID = S.STID
WHEN MATCHED THEN
    UPDATE SET T.NAME = S.NAME
WHEN NOT MATCHED BY TARGET THEN
    INSERT (STID, NAME) VALUES (S.STID, S.NAME)
WHEN NOT MATCHED BY SOURCE THEN
    DELETE;


