create table persons1
(
id int primary key ,
name varchar(50) not null,
birth_date date ,
phone int,
)

alter table persons1 alter column phone varchar(15)
ALTER TABLE PERSONS1 ADD MOBILE VARCHAR(12),TELE_PHONE VARCHAR(12),LAND_PHONE VARCHAR(12),PHONE1 VARCHAR(12)

ALTER TABLE PERSONS1 
     RENAME COLUMN PHONE1 TO PHONE2,

EXEC SP_RENAME 'DBO.PERSONS1.id','ID','COLUMN'
EXEC SP_RENAME 'DBO.PERSONS1.NAME','NAME' ,'COLUMN'
EXEC SP_RENAME 'DBO.PERSONS1.BIRTH_DATE','BIRTH_DATE','COLUMN'
EXEC SP_RENAME 'DBO.PERSONS1.PHONE','PHONE','COLUMN'

--ALTER TABLE PERSONS1 MODIFY COLUMN id  TO ID INT 

ALTER TABLE PERSONS1 DROP COLUMN MOBILE


update persons1
set phone ='7989966744'
where id=1

CREATE TABLE [UNIQUE]
(
UN_ID INT PRIMARY KEY,
UN_NAME VARCHAR(20) UNIQUE,
UN_DATE DATETIME DEFAULT GETDATE()
);

--INSERT WILL NOT PERFORMED DUE TO DEFAULT VALUE IS NOT GIVEN 
--INSERT INTO [UNIQUE]
--SELECT 1,'ASHOK'    

--HERE DEFAULT VALUE GIVEN AS SPACE WITH SINGLE QUOTE ITS NOW WORKED

INSERT INTO [UNIQUE]
SELECT 1,'ASHOK','' 

INSERT INTO [UNIQUE] SELECT 2,'KRISHNA','' 
INSERT INTO [UNIQUE] SELECT 3,'PARDHA',''
INSERT INTO [UNIQUE] SELECT 4, 'MUKKA',''

INSERT INTO [UNIQUE]
VALUES (5,'VEERA',''),(6,'RAVI',''),(7,'JAN',''),(8,'FEB',''),(9,'MAR','')

SELECT *FROM [UNIQUE]

SELECT GETDATE()

SELECT *FROM [UNIQUE]
ORDER BY UN_NAME DESC
LIMIT 1
----OFFSET 5

SELECT * FROM table_name
ORDER BY column_name DESC
LIMIT 1
--OFFSET 5;